read name from string
LordLukin/Bowling pull request #11
Opened 2019-02-28 23:05 UTC by MarcinWasik

2019-03-01 09:01 UTC, ziobron requested changes
Sama implementacja jest super :+1: 
Tylko kwestie formatowania i nazewnictwa do małej poprawy :)
Nie masz też wszystkich commitów kiedy zaczynałeś pracę, bo Kasia dostarczyła już wcześniej funkcję `read`, a Ty od nowa ją napisałeś. Warto żebyś zrobił tzw rebase'a aby mieć wszystkie zmiany zanim dostarczysz swoje, bo tak czy inaczej te konflikty będziesz musiał rozwiązać. Gdybyś to zrobił wcześniej to nie musiałbyś drugi raz pisać tego co Kasia dostarczyła.

Sama procedura jak zrobić rebase, jeśli pracujecie na branchu master:
```git
git pull https://github.com/LordLukin/Bowling.git
git mergetool - tutaj będzie rozwiązywanie konfliktów
git commit - to jak rozwiążesz wszystkie konflikty
git push
```

2019-03-01 09:01 UTC, ziobron commented on inc/Game.hpp
> -    // TODO: Add game status: No game, In progress, Finished
Ten TODO może zostać, bo status i tak jeszcze będzie do zrobienia

2019-03-01 09:01 UTC, ziobron commented on .gitignore
> +CMakeLists.txt.user
Wielki plus za wkomitowanie .gitignore. Dzięki temu będziecie mogli w miarę bezpiecznie robić `git add .` i nie dodadzą wam się te rzeczy, które są na tej liście. :+1:

2019-03-01 09:01 UTC, ziobron commented on src/Game.cpp
> +    int placeOfChar = playerAndGame.find(':');
Nazwę tylko sugeruję zmienić na `placeOfColon`, bo colon to dwukropek po angielsku

2019-03-01 09:01 UTC, ziobron commented on src/Game.cpp
> +    name.append(playerAndGame.begin(),playerAndGame.begin()+placeOfChar);
Formatowanie - dawaj spacje po przecinku oraz przed i za plusem.
```cpp
name.append(playerAndGame.begin(), playerAndGame.begin() + placeOfChar);
```

2019-03-01 09:01 UTC, ziobron commented on src/Game.cpp
> +std::string Game::getName(){
Formatowanie - spacja przed {
```cpp
std::string Game::getName() {
```

2019-03-01 09:01 UTC, ziobron commented on tests/GameTests.cpp
> +}
Warto dopisać jeszcze jeden test dla przypadku bez imienia np. `":9-|9-"`

2019-03-01 09:01 UTC, ziobron commented on tests/GameTests.cpp
> +TEST_F(GameTests, Read)
Nazwę testu sugeruję zmienić na `TestNameExtraction`

2019-03-01 17:11 UTC, madza93 approved these changes

2019-03-03 23:36 UTC, LordLukin commented
@MarcinWasik popraw proszę moje uwagi i wrzuć nową wersję jak najszybciej, aby nie blokować innym pracy.

2019-03-04 22:04 UTC, ziobron requested changes

2019-03-04 22:04 UTC, ziobron commented on inc/Game.hpp
> +    void read(const std::string& playerAndGame) throw(std::logic_error);
Nie powinno być tego specyfikatora throw w sygnaturze funkcji. Jest to element przestarzały i ten kod się nie skompiluje w C++17, bo został on usunięty z języka w 17 właśnie.

2019-03-04 22:04 UTC, ziobron commented on inc/Game.hpp
> +#include <iostream>
Niepotrzebny include, nigdzie nie są używane strumienie takie jak cout.

2019-03-04 22:04 UTC, ziobron commented on src/Game.cpp
> +        throw std::logic_error("Invalid name");
Ze specyfikacji raczej nie wynika, żeby zabraniać gry, jeśli gracz nie podał swojego imienia. W przykładach tutaj https://github.com/LordLukin/Bowling po prostu jest to gracz z pustym imieniem, więc ta zmiana nie jest potrzebna.

2019-03-09 19:35 UTC, ziobron approved these changes
Looks good, Squash & Merge :)

2019-03-17 12:23 UTC, merged