implement read frames
LordLukin/Bowling pull request #13
Opened 2019-03-03 20:27 UTC by Kasix91

please review and comment

2019-03-03 23:34 UTC, ziobron requested changes
Najważniejsze są testy. Musisz jakieś dodać. Najlepiej to gdybyś od nich zaczęła, czyli zastosowała TDD.

2019-03-03 23:34 UTC, LordLukin commented on CMakeLists.txt.user
> +<?xml version="1.0" encoding="UTF-8"?>
Tego pliku nie chcemy w repo

2019-03-03 23:34 UTC, LordLukin commented on src/Game.cpp
> +void readFrames (std::string frames){
To w funkcji read, którą masz powyżej ma być, więc przenieś to do niej.

2019-03-03 23:34 UTC, LordLukin commented on src/Game.cpp
> +    frames.append(frames.begin() + placeOfPipe+1, frames.end());
Nie jest to poprawna implementacja, ale jeszcze tego nie wiesz, bo nie masz testów :dagger: 
Powinnaś szukać dwukropka, ale wziąć wszystko od niego do końca.

2019-03-13 13:37 UTC, madza93 approved these changes

2024-06-16 05:08 UTC, closed without merging